project:
  type: website

website:
  title: "Nicki's Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    contents:
      - text: "Food"
        href: food_intro.qmd
        contents: 
          - christmas_salad.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
