# Christmas Party Salad

This is how I made the salad for the Christmas party. It's based on two salads from the book *Salad Freak*. It's definitely a labor of love, not a workday lunch salad.

## Ingredients

There are probably lots of ways to modify the ingredients in this salad if you don't have these on hand.[^1] But this is the faithful recording of what I did.

**Stuff**

- 1 bunch dino kale
- 3/4 pound Brussells sprouts
- 1 delicata squash
- 2 medium sumo oranges
- double handful of raw, unsalted pepitas
- 3/4 log of goat cheese

**Dressing**

- olive oil
- avocado oil
- meyer lemon vinegar
- half clove elephant garlic
- white miso paste
- agave nectar
- grainy mustard
- salt
- pepper

## Prep

Some of these are fussy details, but they are important for making a bunch of tough, chewy ingredients (kale, Brussels sprouts, orange segments) easy to eat by the spoonful.

**Oven On**

Turn it on to 400 degrees.

**Delicata Squash**

1. Wash the outside and dry it.
2. Slice the squash in half (hamburger first), then cut those in half (then hotdog style) so that you can scrape the seeds out. Discard seeds.
3. Slice the squash into spears, then slice the spears into bite sized pieces.
4. Toss with olive oil and salt. Probably more salt than you think.
5. Lightly oil a baking sheet and spread the squash out on it. Leave space between pieces for steam to escape and encourage browning.
6. Roast for 20 minutes. Don't move them. They'll get dark golden brown, probably browner than you think. This is good. Resist the urge to pull them out early.
7. Let them cool out of the way. Don't eat them all while you prep rest of salad.

**Brussells Sprouts**

1. Wash the sprouts.
2. Trim the brown skin off the butt and any ugly leaves. Discard these.
3. Pull the outer few leaves off of each sprout, the ones that come off pretty easily. Once the leaves wrap really tightly to each other like a teeny cabbage, you can leave them.
  - Put the leaves in a bowl.
  - Put the tiny cabbages off to the side.
4. Toss the outer leaves with oil and salt.
5. Lightly oil a baking sheet and spread the leaves out on it. Leave space between pieces for steam to escape.
6. Roast for 9 minutes. Don't move them. They'll get dark brown in places and you'll probably be scared that they're burned, and they might even taste pretty dark, but don't worry. They'll add nice complexity to the salad.
7. Set the leaves off to the side.
  
Return the tiny cabbage-looking Brussells back to your working area. Slice them whisper thin on a mandolin, holding the stem end.

- I used the thinnest setting on my mandolin.
- I only sliced about 3/4 of each sprout. I'm scared of cutting my fingers. I'll use the leftovers in something else since they'll roast up nicely.
- Put the shreds in a big bowl off to the side.

**Pepitas**

Fresh toasted pepitas are nice, add crunchy and toasty smells.

1. Spread the seeds out on a sheet pan.
2. Roast for 3 minutes until they're fragant. Set a timer. Burnt nuts stink.
3. Cool them on a bowl or plate out of the way.

**Prep Kale**

1. Wash kale in big bowl cold water and then spin it dry.
2. Slice the dark green leafy parts off the stems.[^2]
3. Stack some leaves and then slice those into super thin ribbons (can chiffonade them if you're fancy.)
4. Add these to the bowl with the raw Brussells sprouts shreds.


**Prep Oranges**

1. Peel the oranges.
2. Break the oranges into quarters, leaving 3-4 segments stuck together.
3. Slice these segments thinly across the "grain"; you'll end up with flat pieces shaped like quarter-circles.
4. Pile into a bowl off to the side.


**Goat Cheese**

1. Crumble into biggish bite sized pieces (they'll get smaller later when you toss the salad.)
2. Set off to the side.


**Garlic**

1. Peel the garlic and discard skins.
2. Grate the garlic on a microplane.
3. Drop into a medium bowl (this is the bowl we'll mix the dressing in later.)


## Steps

### Mix Dressing

I made this up as I went. The following proportions are estimated.

1. Pour like 1/3 or 1/2 cup oil into dressing bowl (the one that has the grated garlic).
2. Pour vinegar into the bowl (I visualize about 1 part vinegar to 4 parts oil.)
3. Squeeze in probably a tsp of agave nectar.
4. Squeeze in the same amount of miso paste.
5. Squeeze in probably 1/2 tsp of mustard.
6. Add a bunch of fresh ground black pepper.
7. Add a big pinch of salt.
8. Add a couple spoonfuls of water.
9. Mix with a fork until emulsified.
    
Taste and adjust. If it's too vinegary, add a little more oil, salt, and agave. If it's too thick, add another spoonful of water. Add salt if it's bland.

### Mix Bits

1. Add the cooled, roasted Brussells sprouts outer leaves to the bowl with the shredded kale and sprouts.
2. Add a pinch of salt or 2 to the leaves
3. Mix with tongs like crazy until its a big heap of garden confetti.
4. Add the dressing to the leaves and mix and mix again until everything is a little coated and oily and moist.
5. Add the pretty parts at the end so that they don't get beat up or crushed. I like to pull the greens to the edge of the bowl and add half the cooled squash, pumpkin seeds, orange slices, and goat cheese. Then fold the greens from the sides back in and add the rest of the goodies.
6. Toss gently, just enough to distribute the goodies but not so much that the oranges fall apart or the goat cheese get too crushed.


[^1]: For example,

    - apple cider vinegar instead of meyer lemon vinegar,
    - 2 cloves regular garlic instead of elephant garlic,
    - leave out the miso paste (it's a subtle addition)

[^2]: Stems are woody and unpleasant to chew. Discard them or get clever and find a way to repurpose them.